# Generated by Django 2.0.5 on 2018-05-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagetory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cagetory',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='Blog.Cagetory'),
        ),
    ]
