# Generated by Django 2.0.5 on 2018-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugifytitle',
            field=models.SlugField(null=True),
        ),
    ]
