# Generated by Django 2.0.5 on 2018-05-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_cagetory_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cagetory',
            old_name='name',
            new_name='title',
        ),
    ]
