# Generated by Django 2.0.5 on 2018-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20180529_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugifytitle',
            field=models.CharField(default='THISISNOTHING', max_length=100),
        ),
    ]
