# Generated by Django 2.0.5 on 2018-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20180529_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugifytitle',
            field=models.CharField(default='d', max_length=100),
        ),
    ]
